### ISSUE TITLE
python3 formatting bug

### ISSUE THREAD

**Issue by fsiler** [truongkma/ctf-tools#1]
prints eg

`b'tacc.pdf':b'$pdf$4*4*128*-1084*1*16*4efe81154d8d334ca7c2237d6fa33b7c*32*dca60d6922b098cfb0f36c9bd43b581600000000000000000000000000000000*6*b67c49948b34':::::file.pdf`

instead of 

`tacc.pdf:$pdf$4*4*128*-1084*1*16*4efe81154d8d334ca7c2237d6fa33b7c*32*dca60d6922b098cfb0f36c9bd43b581600000000000000000000000000000000*6*b67c49948b34:::::file.pdf`

**Comment by truongkma** [comment]
@fsiler I'm sorry. This respo user for personal use. I have not used it for a long time.
