### ISSUE TITLE
need owner hash....I think?

### ISSUE THREAD

**Issue by fsiler** [truongkma/ctf-tools#2]
I have encountered [a most unusual PDF](http://www.sbids.org/forms/tacc.pdf), and no matter what I do- whether I use the Perl or Python `pdf2john` scripts, I seem to get a hash that either won't work at all with any hashcat/John method, OR I get `$pdf$4*4*128*-1084*1*16*4efe81154d8d334ca7c2237d6fa33b7c*32*dca60d6922b098cfb0f36c9bd43b581600000000000000000000000000000000*32*b67c49948b34299fdea1cae70b9a097f724f084385092a51473dcf617bb19c1b`, which is a blank password.

Using Didier Steven's `pdfid.py` and `pdf-parser.py`, I have observed some odd entries in Object 33- or at least they look odd to me.  Anyone care to have a look at this file and make it possible to work on the key?  Thanks.

**Comment by truongkma** [comment]
@fsiler I'm sorry. This respo user for personal use.  I have not used it for a long time.
